### ISSUE TITLE
Document OData spec in detail

### ISSUE THREAD

**Issue by mleegwt** [DigitaleDeltaOrg/dd-api-v3#5]
In https://github.com/DigitaleDeltaOrg/dd-api-v3/blob/main/definition/csdl/v2023.01/csdl.xml there are various fields which can be hard to interpret or need explanation. 
E.g. 
- Id, why a String
- In Result: How many of the optional fields are expected to be filled?
- Uom: Probably Unit of Measure
- CategoryVerb: it's purpose and how to apply the fields.
- DefaultPointMetaData: what is the purpose of this field?
- TimeserisMetadata.Spacing: what is the purpose of this field and how should it be filled?
- NilReason: what is the purpose of this field? (nil could mean empty but also zero... not a generic term for everyone)

Could the specification be improved by using comments or annotations?
E.g. one of the options below:
```
<Property Name="ProductName" Type="Edm.String">
  <!-- This is the name of the product -->
  <Annotation Term="MyNamespace.Description" String="The name of the product." />
</Property>
```

**Comment by mleegwt** [comment]
I think this issue was not yet completed. #6 probably is.
What is the meaning of the newly added file in commit: https://github.com/DigitaleDeltaOrg/dd-api-v3/commit/2fd18e127bbf93d3e1306160e7434a9e55d915e7 ?

**Comment by GeriWolters** [comment]
Correct. My apologies. I didn't even see the issue created yet (I was on vacation then). Thanks for the heads-up and the issue!

Regarding Ids: String is the easiest format to use. it should be unique and should be consistent and persistent. Normally, I would use a UUID, but not all systems have their external identifiers defined as UUIDs. Forcing UUIDs would force changes to the underlying systems, which would decrease adoptation. Strings are a decent middle-of-the-road.

UoM indeed is Unit of Measurement.

CategoryVerb is described in OM&S. Basically, it defines a category and verb, similar to what RDF uses.

DefaultPointMetadata is also part of OM&S. PointMetadata applies to time series. The default specifies the defaults for it.

TimeseriesMetadata.Spacing is not required. It is useful in scenario;s where the data is guaranteed to be equidistant in time. It then reduces the data volume.

NilReason is meant to be used in cases where no data is available within the time series or observation. 

XML can use comments, ofcourse. I will try add comments to it. I am not sure if annotations would break the definition. Since comments won't break, I'd prefer that.

Kind regards,

   Geri

**Comment by GeriWolters** [comment]
The newly added file will be a replacement for the current semantic definition. It basically is a list of known entity/property combinations and their types. I have (almost) finished tooling now that can validate de OData $metadata of a service with that file (and version of it) and determine what is missing, or what is unknown. 
The fiile is not final yet: it needs to be discussed with Informatiehuis Water (IHW). Changes that I forsee: parameter/parameter (confusing) will be split into parameter/biotaxon, parameter/chemical, parameter/physical.

We (Digitale Delta community) will only need to maintain (a version of) that file to check for compliance.
Ofcourse, we won't be able to validate the data in the responses, but since OData is controlling query and responses, it will go a long way.
